# Snowflake values
X_TRANSFORM = 20
Y_TRANSFORM = 20
SNOWFLAKE_IMG_OFFSET = 30

# Display values
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

# Grid values
GRID_ROWS = 50
GRID_COLS = 50
BLOCK_WIDTH = SCREEN_WIDTH // GRID_COLS
BLOCK_HEIGHT = SCREEN_HEIGHT // GRID_ROWS

# Snowplow values
SP_X_TRANSFORM = 20
SP_Y_TRANSFORM = 20
SNOWPLOW_IMG_OFFSET = 10
MOVE_X = BLOCK_WIDTH
MOVE_Y = BLOCK_HEIGHT

# Snowpile values
Snowpile_X_TRANSFORM = 20
Snowpile_Y_TRANSFORM = 20


# Colors
BLACK = [0, 0, 0]
WHITE = [255, 255, 255]

# Stats
CARRY_X = 20
CARRY_Y = 15
SCORE_X = 20
SCORE_Y = 50
DISTANCE_X = 20
DISTANCE_Y = 85
COLLISION_X = 20
COLLISION_Y = 120
SNOWPILE_X = 20
SNOWPILE_Y = 155
