# Snowflake values
X_TRANSFORM = 20
Y_TRANSFORM = 20
SNOWFLAKE_IMG_OFFSET = 30

# Display values
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

# Grid values
GRID_ROWS = 50
GRID_COLS = 50
BLOCK_WIDTH = SCREEN_WIDTH // GRID_COLS
BLOCK_HEIGHT = SCREEN_HEIGHT // GRID_ROWS

# Snowplow values
SP_X_TRANSFORM = 35
SP_Y_TRANSFORM = 35
SNOWPLOW_IMG_OFFSET = 25
MOVE_X = BLOCK_WIDTH
MOVE_Y = BLOCK_HEIGHT

# Colors
BLACK = [0, 0, 0]
WHITE = [255, 255, 255]

# Stats
SCORE_X = 20
SCORE_Y = 15
DISTANCE_X = 20
DISTANCE_Y = 50
COLLISION_X = 20
COLLISION_Y = 85
