# Snowflake values
X_TRANSFORM = 20
Y_TRANSFORM = 20
SNOWFLAKE_IMG_OFFSET = 32

# Display values
SCREEN_WIDTH = 987
SCREEN_HEIGHT = 964

# Grid values
GRID_ROWS = 50
GRID_COLS = 50
BLOCK_WIDTH = SCREEN_WIDTH // GRID_COLS
BLOCK_HEIGHT = SCREEN_HEIGHT // GRID_ROWS

# Snowplow values
SNOWPLOW_IMG_OFFSET = 30
MOVE_X = BLOCK_WIDTH
MOVE_Y = BLOCK_HEIGHT

# Colors
BLACK = [0, 0, 0]
WHITE = [255, 255, 255]